@startuml


package "Domain" {
class User {
String username
int id
DateTime lastSignIn
String password

User(String name)
toString()
getId()
getPassword()
getLastSignin()
}

class Channel {
Int ID
String name;
Channel(int ID, String name)
}

class Subscription {
User user
Channel channel
enum rights
DateTime timestamp
}

interface SubscriptionRepository{
subscribeToChannel(User user, Channel channel)
}

interface SubscriptioFactory{

}

interface MessageRepository {
+getMessages(int limit)
+getMessage(int id)
}

interface MessageFactory{
}

class Message {
int id
String messageText
DateTime timestamp
User user
+Message(User user, String message)
}
}

package "entries" {
class Server {
}
class Chat {
userOnline()
}

class CmdLine {
login(User user)
createUser()
passwordValidation()
}
}

package "infrastructure" {
class Database {
}
}

package UI {
class Menu {
login(User user)
createUser()
}
}






@enduml