package chadchat.entries;

import java.sql.*;

// Forsøg på at Insert og returnere et autogenerated ID

public class CreateChannel {

    // The entry point of the ChatChad server

    // JDBC driver name and database URL
    static final String JDBC_DRIVER = "com.mysql.cj.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://104.248.135.65/ChadChat";

    //  Database credentials
    static final String USER = "chadchat";
    static final String PASS = "familiebil";

    private static void createChannel(String name) throws ClassNotFoundException {
        Class.forName(JDBC_DRIVER);
        try (Connection conn = DriverManager.getConnection(DB_URL, USER, PASS)) {
            String sql;
            sql = "INSERT INTO Channels(name) VALUES (?)";

            PreparedStatement stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
            stmt.setString(1, name);
            stmt.executeUpdate();

            ResultSet rs = stmt.getGeneratedKeys();

            rs.next();

            int id = rs.getInt(1);
            System.out.println(id);

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    public static void main(String[] args) throws SQLException, ClassNotFoundException {
        // Remove this soon
        createChannel("Peter");
    }

}

/*
DROP TABLE IF EXISTS Channels;
CREATE TABLE Channels (
    id int NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
);
 */


